### ISSUE TITLE
Did you manage to fix it ?

### ISSUE THREAD

**Issue by volodymyr-tsaryk** [iamdey/RD-webpack4-code-split#1]
Hello @iamdey 
I have an exactly same issue, did you find a solution for it?

Regards,
Volodymyr

**Comment by iamdey** [comment]
actually yes. 

We found a fix duplicating the loaded script into vendor and app entry or by importing the script directly from source code.

More details here: https://stackoverflow.com/questions/50062264/webpack-4-code-splitting-and-var-injection/50068935#50068935
